### ISSUE TITLE
Does this work anymore? is it replaced with chrome-zauth-plugin?

### ISSUE THREAD

**Issue by imduffy15** [zalando-incubator/chrome-oauth-bearer-plugin#17]
Does this work anymore? Is it replaced with https://github.bus.zalan.do/mask/chrome-zauth-plugin/

If so can we update the readme to point to this other project?

**Comment by gilvegliach** [comment]
@imduffy15 Hello Ian, the project you linked was meant to replace this one inside Zalando. This project still remains of general interest. Further, note that the link you posted is from GHE, i.e. company-private. I don't think it is a good idea to put it here or in a public README. Let's ask the opinion of @LappleApple
